name: CI/CD Pipeline  # Workflow name

on:  
  push:
    branches:
      - main  # Run the job when code is pushed to "main" branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on an Ubuntu server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Get the latest code

      - name: Install Dependencies
        run: npm install  # Installing project dependencies

      - name: Run Tests
        run: npm test  # Running tests

  deploy:
    needs: build  # Only run if "build" job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        run: echo "Deploying to AWS..."  # Fake deploy command
